Online course web site
karam084/online-course pull request #1
Opened 2021-11-20 17:41 UTC by karam084

*- The project solve this 

- Colors.
- Typography: font face, size and weight.
- Layout: composition and space between elements.
- The home page.
- The about page.
- Mobile: up to 768px wide.
- Desktop: 768px or wider.
- The home page should have a link in the menu to the about page.
- The logo in the header links to the home page.
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
- The mobile menu should have a close (X) button that closes the menu.
- Dynamic page

2021-11-20 18:55 UTC, carlos-ssh requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#

Hi @karam084 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._ 


![changesrequested](https://user-images.githubusercontent.com/22258274/139840240-ea0d564a-492a-44e3-87af-8d5830ab0d6d.gif)
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-20 18:55 UTC, carlos-ssh commented on index.html
> +      <!--<h3 class="feature">Featured Speakers</h3>
- Kindly remove commented code.

2021-11-20 18:55 UTC, carlos-ssh commented on js/mobile-menu.js
> +  }, */
- Kindly remove commented code.

2021-11-20 18:55 UTC, carlos-ssh commented on index.html
> +      <div class="feature-s">
## Video presentation
1. Record a video presenting the features of the project.
1. The maximum length of the video is 5 minutes.
1. The video need to have a clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
1. The video need to have a demo of the project, showing the pages in different screen sizes.
1. The video need to have a highlight about a piece of the code the student finds interesting or is proud of making.

2021-11-20 18:55 UTC, carlos-ssh commented on index.html
> +        <h3 class="pers-name">Abdel Rahman</h3>
## Live version

1. Kindly make use of GitHub Pages to deploy the web pages.
1. The project should be deployed properly, all pages, links, and images work as expected.
1. Add a link to the deployed project is present in the README.

2021-11-20 18:55 UTC, carlos-ssh commented on index.html
> +          Vice President for Reasearch and Postgraduates Affairs
- Kindly display properly the images and follow the requested design for your project:

**Your project running locally:**
![Screen Shot 2021-11-20 at 12 50 06](https://user-images.githubusercontent.com/22258274/142737874-fe448a27-7eb4-4a99-aa7c-1f426950f328.png)
![Screen Shot 2021-11-20 at 12 50 14](https://user-images.githubusercontent.com/22258274/142737875-67afca1c-d8c3-452c-bce8-895a45d83158.png)
![Screen Shot 2021-11-20 at 12 50 32](https://user-images.githubusercontent.com/22258274/142737876-6bf3f1b9-d226-4ce8-a418-e938eaeac801.png)
<img width="1408" alt="Screen Shot 2021-11-20 at 12 50 53" src="https://user-images.githubusercontent.com/22258274/142737877-e11f8d40-3311-4d48-afb5-e36fd80179fe.png">


- Follow the design guidelines requested you can go to the link [here.](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
- Kindly check your project requirements before to request another code review.

2021-11-26 05:12 UTC, oxenprogrammer requested changes
Hi @karam084, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## Suggested changes
- [ ] Good effort with the video. However, you are required to explain a particular piece of code that you're excited about. Please let us record another video and include that bit.
- [ ] The mobile version is currently distorted as shown in the video below. Let us try and fix it.

https://user-images.githubusercontent.com/7220167/143530195-0c56474b-e3ff-4017-9fa8-88c332e77f81.mp4



_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-11-26 05:12 UTC, oxenprogrammer commented on Css/about.css
> +  }
**Suggested Changes**
- [ ] There is quite a lot of repeated css rules all over the codebase. For instance in these two hightlighted snippets, `display: flex;` and `flex-direction: column;` is being repeated. Please create a `global className` to group together these css rules. This will help your codebase adhere to the `DRY` principle.

2021-11-26 05:12 UTC, oxenprogrammer commented on js/feature.js
> +];
**Suggested Changes**
- [x] Array `speakers2` is the same as Array `speakers`. This is unnecessary code duplication. Please let us merge both arrays into one to try and keep our codebase `DRY`.

2021-11-26 05:12 UTC, oxenprogrammer commented on js/feature.js
> +              </div>
**Suggested Changes**
- [x] The hard-coded `HTML5` here mixes JavaScript and HTML5 code. Remember the `SOLID` principle? The `S` stands for `Separation of Concern`. You can create the HTML5 on the fly using `document.createElement()` and dynamically attach it to the `DOM`. Let us please try and do so to adhere to the `SOLID` principle, in this way we will increase `readability`.

2021-11-26 05:12 UTC, oxenprogrammer commented on Css/style.css
> +}
**Suggested Changes**
- [x] We will need to fix the horizontal scroll to avoid overlap. Below is a video of what I mean.

https://user-images.githubusercontent.com/7220167/143527560-48242ec3-1f1f-4b7c-8a45-d997c9e78e51.mp4

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +      </nav>
**Suggested Changes**
- [ ] The height of this first navigation bar is higher than that of the provided design on Desktop. Please let us reduce the height just like the design. Remember we have to adhere to the layout provided.

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +      <div class="menu-overlay hide-menu">
**Suggested Changes**
- [ ] The menu is currently aligned to the left. From the design, this should be `centered`. Let us make these changes please.

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +      <p class="address">@Haram Giza Egypt</p>
**Suggested Changes**
- [x] The `font-size` does not currently match that provided in the design. Please let us work on it.
- [x] The text `Activities and events for the new online training courses 2021` should be in **UPPERCASE**

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +    </section>
**Suggested Changes**
- [ ] The background color doesn't match that provided in the design. Let us please work on it.
- [x] The `h3` in className `.border-box` are currently left-aligned. They should be `center-aligned`
- [x] The text `Main Program` should be `bold` with an `orangish underline`
- [x] The `.border-box` shape doesn't resemble the provided design. Yours is a rectangle while that in the design is an inverted rectangle.

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +    </section>
**Suggested Changes**
- [ ] This is not currently aligning well.

Your Design
![speackers](https://user-images.githubusercontent.com/7220167/143529416-f85652f1-3165-43f3-b222-4381614be607.png)

Provided Design
![real-speakers](https://user-images.githubusercontent.com/7220167/143529497-152889c7-a539-4e28-81b2-22bfddb7f890.png)

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +        <span class="under-lll"></span>
**Suggested Changes**
- [ ] The `underline` is currently displaced as shown below. Let us please fix it.
![underline](https://user-images.githubusercontent.com/7220167/143529639-01d59cbb-6e46-4442-93a7-32bc9922243a.png)

2021-11-26 05:12 UTC, oxenprogrammer commented on index.html
> +      </footer>
**Suggested Changes**
- [ ] The footer should be centered as in the design. Yours is currently left-aligned. Let us make these chnages

2021-11-27 20:26 UTC, sheylaPozo commented
## Status: ✔️ Project Approved ✔️ 
----

Hello @karam084  🔥 

> # Excellent work on your project, it looks very professional and it's completed. Congrats on the good work!

- [ ]  Make sure to check the optional changes suggested below, to improve your project's final view.

![surprised](https://user-images.githubusercontent.com/60631456/122959988-c881fc00-d348-11eb-988a-a5aa782f4777.gif)

Now you can celebrate! 🥇 🚀 👍 💯 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️
`There's nothing left to say but time to merge! 😊`

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 20:37 UTC, sheylaPozo commented
## Optional Suggestions 
---
When viewing your project's mobile version I noticed your hamburger button doesn't show in the full dimensions of the page opened...

Example version    | Your Mobile version
-------------------- | ----------------------
![S](https://user-images.githubusercontent.com/54015740/143721459-94fb911e-b3d3-44e4-babc-0cd7757f722b.png) | ![Mobile](https://user-images.githubusercontent.com/54015740/143721434-e48e87d3-c324-481a-9d59-a946d4766ba4.png)
- [x] For the example I'm using an old project just for demonstration purposes, but that's sort of how the hamburger button had to go here, to look more accurate with this capstone template. 
- [ ]  Also notice that your links aren't directing us to anywhere, when clicking on the links of your hamburger button, you should be able to be redirected to the sections your project was indicating like for example, clicking on the about section, should redirect us to about section.  Please implement these changes for your project's professional look, and to improve more in your journey as a developer. 

✔Your project will look better if you would implement this changes 😄👍 💯 

![tenor](https://user-images.githubusercontent.com/54015740/127129480-dfb12898-5429-4ff7-a67a-f4e3df0edc64.gif)

2021-11-27 20:40 UTC, merged